#!/bin/bash

echo "Build hook running"

VERSION=$(cat VERSION)

echo "Building for x84_64..."
docker build -t $DOCKER_REPO:$VERSION -f Dockerfile .

# FIXME how to use post_checkout to support arm builds?
#echo "Building for arm32v6..."
#docker build -t $DOCKER_REPO:$VERSION-arm --build-arg BASEIMG=arm32v6/python:3.6.4-alpine3.7 -f Dockerfile .